<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report</title>
    <style>
        
        @import "bootstrap/scss/bootstrap";

        /* Include your CSS styles here */
        body {
    font-family: 'Plus Jakarta Sans', sans-serif;
    background-color: #f8f9fa;
}

.container {
    background-color: white;
    padding: 2rem;
    border-radius: 10px;
    margin-top: 2rem;
}

.table {
    width: 100%;
    margin-bottom: 1rem;
    color: #212529;
}

.table th, .table td {
    padding: 0.75rem;
    vertical-align: top;
    border-top: 1px solid #dee2e6;
}

.table thead th {
    vertical-align: bottom;
    border-bottom: 2px solid #dee2e6;
}

.table tbody + tbody {
    border-top: 2px solid #dee2e6;
}

.card {
    margin-bottom: 1rem;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.125);
    border-radius: 0.25rem;
}

.card-header {
    padding: 0.75rem 1.25rem;
    margin-bottom: 0;
    background-color: rgba(0, 0, 0, 0.03);
    border-bottom: 1px solid rgba(0, 0, 0, 0.125);
}

.card-body {
    padding: 1.25rem;
}

.btn-primary {
    background-color: #007bff;
    border-color: #007bff;
}

.btn-secondary {
    background-color: #6c757d;
    border-color: #6c757d;
}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Publication Report</h1>
        </div>
        <div class="card">
            <h2>Report Summary</h2>
            <p>Report generated on: {{ $reportDate }}</p>
            <p>Total publications: {{ $totalPublications }}</p>
            @if($filterType == 'university')
                <p>University: {{ $filterValue }}</p>
            @elseif($filterType == 'platinumName')
                <p>Platinum Name: {{ $filterValue }}</p>
            @endif
        </div>
        <div class="card">
            <h2>Publication List</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Authors</th>
                        <th>Type</th>
                        <th>Published Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($publications as $publication)
                        <tr>
                            <td>{{ $publication->P_title }}</td>
                            <td>{{ $publication->P_authors }}</td>
                            <td>{{ $publication->P_type }}</td>
                            <td>{{ $publication->P_published_date }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="footer">
            <p>Generated by Platinum Orbit System</p>
        </div>
    </div>
</body>
</html>
